### 增加货物
POST {{Domain}}/good/addGood
Content-Type: application/json
authorization:{{TOKEN}}

{
  "id": "13344",
  "name": "esp32",
  "size": 32,
  "user_name": "Agoines"
}


### 删除货物
POST {{Domain}}/good/delGood
Content-Type: application/json
authorization:{{TOKEN}}

{
  "good_id": "12"
}

### 查找对应货物
POST {{Domain}}/good/searchGood
Content-Type: application/json
authorization:{{TOKEN}}

{
  "good_name": ""
}

### 获取货物列表
POST {{Domain}}/good/getGoodList
authorization:{{TOKEN}}

### 更新货物
POST {{Domain}}/good/updateGood
authorization:{{TOKEN}}
Content-Type: application/json

{
  "id": "13344",
  "name": "esp86-air",
  "size": 1,
  "user_name": "Agoines"
}

### 判断货物是否存在
POST {{Domain}}/good/hasGood
Content-Type: application/json
authorization:{{TOKEN}}

{
  "good_id": "13344"
}