### 登录
POST {{Domain}}/user/login
Content-Type: application/json

{
  "username": "agoines",
  "password": "qwer1234",
  "auto_login": false
}

### 注册
POST {{Domain}}/user/signup
Content-Type: application/json
authorization:{{TOKEN}}

{
  "username": "夜白",
  "password": "qwer1234",
  "is_administrator": false
}

### 是否是自动登录
POST {{Domain}}/user/autologin
authorization:{{TOKEN}}

### 删除用户
POST {{Domain}}/user/delUser
Content-Type: application/json
authorization:{{TOKEN}}

{
   "username": "夜白"
}

### 查找对应用户
POST {{Domain}}/user/searchUser
Content-Type: application/json
authorization:{{TOKEN}}

{
   "username": "agoine"
}

### 获取用户列表
POST {{Domain}}/user/getUserList
authorization:{{TOKEN}}

### 更新用户
POST {{Domain}}/user/updateUser
authorization:{{TOKEN}}
Content-Type: application/json

{
  "username": "夜白",
  "password": "agoines",
  "is_administrator": true
}

### 获取用户名字
POST {{Domain}}/user/getUsernameList
authorization:{{TOKEN}}

### 用户对应的货物
POST {{Domain}}/user/getGoods
authorization:{{TOKEN}}
Content-Type: application/json

{
   "username": "agoines"
}

