POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "agoines",
  "password": "qwer1234",
  "auto_login": false
}

### signup
POST http://localhost:3000/user/signup

### hello world
GET http://localhost:3000/


### /getGoodList
POST http://localhost:3000/good/getGoodList
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRvX2xvZ2luIjpmYWxzZSwidXNlcm5hbWUiOiJhZ29pbmVzIiwicGFzc3dvcmQiOiJxd2VyMTIzNCJ9.ZiOf06Dd5D9Omc_XyXrntPNL27vr1WiWQevwK7bUMb0

### /addGood
POST http://localhost:3000/good/addGood
Cookie: TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjU1NjkzMDgsInVzZXJuYW1lIjoiYWdvaW5lcyIsInBhc3N3b3JkIjoicXdlcjEyMzQifQ.b33bpQcAYSNCE_6nH8dTLgJNdBT2WG9mhIiRoQtw6G8;
Content-Type: application/json

{
  "id": "12",
  "name": "esp86",
  "size": 32,
  "user_name": "Agoines"
}
### /delGood
POST http://localhost:3000/good/delGood
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdXRvX2xvZ2luIjpmYWxzZSwidXNlcm5hbWUiOiJhZ29pbmVzIiwicGFzc3dvcmQiOiJxd2VyMTIzNCJ9.ZiOf06Dd5D9Omc_XyXrntPNL27vr1WiWQevwK7bUMb0
Content-Type: application/json

"123"
